import { describe, it, expect, vi, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Stable identity across sessions and assessments.
 *
 * WHY THIS FILE EXISTS.
 *
 * The participant row is the durable identity in this product: the Set for Life
 * Number lives on `participants` (not on a session), a participant owns many
 * assessment_sessions, and the per-assessment sequence (`assessment_number`) is
 * a system fact. Three code paths have to agree on that, or a returning
 * participant quietly loses the thing that lets them come back:
 *
 *   1. POST /api/session takes an EXISTING participant_id and must RESOLVE it,
 *      never mint a second participant. A route that minted one to satisfy a
 *      request would fork a participant's history into two rows and issue them a
 *      second Set for Life Number — silently breaking "the same Participant ID
 *      and Set for Life Number survive" (§5).
 *
 *   2. Provisional creation (`createProvisionalParticipant`) inserts an EMPTY
 *      participant row: no name, no contact, and crucially NO sfl_number. The
 *      Set for Life Number is generated by a database trigger so there is
 *      exactly one implementation of it. If the app computed or supplied one, a
 *      second caller (an import, a backfill) could bypass the trigger and
 *      produce a number that was never checked for collision.
 *
 *   3. Session creation must NOT supply `assessment_number`. The per-participant
 *      sequence is a trigger's job; if the route picked the number it would
 *      reproduce the original `DEFAULT 1` collision that blocked a returning
 *      participant from ever starting a second assessment.
 *
 * The previous coverage (assessment-lifecycle.test.ts REQ 9/10/11/14) pinned the
 * SHAPE of route.ts as source text: a `/participantId/` substring match and the
 * ABSENCE of `createProvisionalParticipant`. Those stay green while the route
 * does the wrong thing — a participant insert can be added anywhere, or an
 * assessment_number hardcoded into the payload, and every grep passes. This file
 * drives both app/api/session/route.ts and lib/session/provisional.ts through a
 * RECORDING fake db and asserts on the actual write set and payloads, and it
 * extracts the migration trigger bodies to check the RAISE / MAX conditions
 * rather than a bare function-name substring. The migration content checks are
 * the one place text assertions are legitimate: there is genuinely no runtime
 * path (live Supabase is BLOCKED_ENVIRONMENT), so the SQL file IS the behaviour.
 */

vi.mock("server-only", () => ({}));

const isDbConfigured = vi.fn(() => true);
vi.mock("@/lib/db/client", () => ({
  isDbConfigured: () => isDbConfigured(),
  isDatabaseConfigured: () => isDbConfigured(),
  getServiceClient: vi.fn(),
  serviceClient: vi.fn(),
  DbNotConfiguredError: class extends Error {},
  errorBody: (code: string, message: string) => ({ error: { code, message } }),
}));

const repo = resolve(__dirname, "../..");
const read = (p: string) => readFileSync(resolve(repo, p), "utf8");

/** The body of a PL/pgSQL function, between its `$$ ... $$` markers. */
function functionBody(sql: string, name: string): string {
  const at = sql.indexOf(`FUNCTION ${name}()`);
  if (at < 0) throw new Error(`function ${name}() not found in migration`);
  const open = sql.indexOf("$$", at);
  const close = sql.indexOf("$$", open + 2);
  return sql.slice(open + 2, close);
}

/**
 * The body with comments and string literals removed — STRUCTURE only.
 *
 * A naive `toMatch(/RAISE EXCEPTION/)` is satisfied by the word appearing in a
 * comment, inside a message text, or in dead code after `IF FALSE AND ...`.
 * Reducing to structure first, then asserting on the extracted condition and
 * action, is what makes these checks fail when the guard stops guarding.
 */
function sqlStructure(body: string): string {
  return body.replace(/--[^\n]*/g, "").replace(/'(?:[^']|'')*'/g, "''");
}

/** Collapse whitespace so a condition can be compared as one string. */
const oneLine = (s: string) => s.replace(/\s+/g, " ").trim();

/**
 * All whitespace removed — for comparing SQL fragments whose exact line
 * wrapping is irrelevant but whose tokens must match exactly.
 */
const squash = (s: string) => s.replace(/\s+/g, "");

interface TriggerDecl {
  name: string;
  timing: string;
  event: string;
  table: string;
  fn: string;
}

/**
 * Trigger declarations as structured facts. A bare
 * `/BEFORE INSERT ON participants/` is satisfied by the words appearing in a
 * comment, or by a DIFFERENT trigger with that wiring; parsing the declaration
 * (comments stripped) pins which trigger fires on what, and which function it
 * executes.
 */
function triggerDecls(sql: string): TriggerDecl[] {
  const clean = sql.replace(/--[^\n]*/g, "");
  return [
    ...clean.matchAll(
      /CREATE TRIGGER\s+(\w+)\s+(BEFORE|AFTER)\s+(INSERT|UPDATE|DELETE)\s+ON\s+(\w+)[\s\S]*?EXECUTE FUNCTION\s+(\w+)\(\)/g,
    ),
  ].map((m) => ({ name: m[1], timing: m[2], event: m[3], table: m[4], fn: `${m[5]}()` }));
}

/**
 * The IF/THEN blocks of a PL/pgSQL body, in source order, as
 * { condition, action } pairs. Used to prove a guard is LIVE (its condition is
 * the real one, not conjoined with FALSE) and that its action is the refusal it
 * is supposed to be.
 */
function ifBlocks(body: string): Array<{ condition: string; action: string }> {
  const clean = sqlStructure(body);
  return [...clean.matchAll(/IF\s+([\s\S]*?)\s+THEN([\s\S]*?)\bEND IF\b/g)].map((m) => ({
    condition: oneLine(m[1]),
    action: oneLine(m[2]),
  }));
}

interface Captured {
  calls: Array<{ table: string; op: string }>;
  inserts: Array<{ table: string; payload: Record<string, unknown> }>;
}

interface FakeDbOptions {
  /** Result of `participants.select(...).eq(...).maybeSingle()` (undefined → null). */
  participantRow?: Record<string, unknown> | null;
  participantSelectError?: { message: string } | null;
  /** Result of `insert(...).select(...).single()`, keyed by table. */
  insertResult?: (table: string) => { data?: unknown; error?: { message: string } | null };
}

/** A recording fake db: it records every table access and every insert payload. */
function fakeDb(opts: FakeDbOptions = {}) {
  const captured: Captured = { calls: [], inserts: [] };

  const db = {
    from(table: string) {
      captured.calls.push({ table, op: "from" });
      return {
        select: (columns: string) => {
          captured.calls.push({ table, op: `select:${columns}` });
          const chain = {
            eq: () => chain,
            maybeSingle: () =>
              Promise.resolve({
                data: opts.participantRow === undefined ? null : opts.participantRow,
                error: opts.participantSelectError ?? null,
              }),
          };
          return chain;
        },
        insert: (payload: Record<string, unknown>) => {
          captured.calls.push({ table, op: "insert" });
          captured.inserts.push({ table, payload });
          return {
            select: () => ({
              single: () => {
                const r = opts.insertResult?.(table) ?? { data: null, error: null };
                return Promise.resolve(r);
              },
            }),
          };
        },
        update: (payload: Record<string, unknown>) => {
          captured.calls.push({ table, op: "update" });
          return { eq: () => Promise.resolve({ error: null }) };
        },
      };
    },
  };
  return { db, captured };
}

function post(body: unknown) {
  return new Request("http://x/api/session", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: body === undefined ? undefined : JSON.stringify(body),
  });
}

async function callPost(body: unknown, opts: FakeDbOptions = {}) {
  const { db, captured } = fakeDb(opts);
  const { serviceClient } = await import("@/lib/db/client");
  vi.mocked(serviceClient).mockReturnValue(db as never);
  const { POST } = await import("@/app/api/session/route");
  const res = await POST(post(body));
  const json = await res.json().catch(() => null);
  return { res, json, captured };
}

const UUID = "12345678-1234-1234-1234-123456789012";

beforeEach(() => {
  vi.clearAllMocks();
  isDbConfigured.mockReturnValue(true);
});

// ===========================================================================
// POST /api/session — resolve an existing participant, never mint one
// ===========================================================================

describe("POST /api/session resolves the participant it is given", () => {
  it("a valid existing participantId returns 201 and inserts ONLY a session", async () => {
    const { res, json, captured } = await callPost(
      // The caller also offers a `name`; the route must not copy unknown fields
      // into the write.
      { participantId: UUID, name: "Ada Lovelace" },
      {
        participantRow: { participant_id: UUID },
        insertResult: (table) =>
          table === "assessment_sessions"
            ? {
                data: {
                  session_id: "s-1",
                  assessment_version: "1.0",
                  status: "in_progress",
                  current_position: 1,
                },
                error: null,
              }
            : { data: null, error: null },
      },
    );
    console.log("  existing participant ->", res.status, JSON.stringify(json));
    expect(res.status).toBe(201);

    const tables = captured.inserts.map((i) => i.table);
    console.log("  tables inserted:", JSON.stringify(tables));
    expect(
      tables,
      "the ONLY write is a session insert — the participant is REUSED, never minted",
    ).toEqual(["assessment_sessions"]);

    const payload = captured.inserts[0].payload;
    console.log("  session insert payload:", JSON.stringify(payload));
    // Exact key set, not just a membership check: this is what fails if the
    // route leaks a caller-supplied field into the row, supplies
    // `assessment_number` itself (the trigger owns it — see the migration
    // test), or silently drops a required column.
    expect(
      Object.keys(payload).sort(),
      "exactly the four system-chosen columns — no caller field passes through",
    ).toEqual(["assessment_version", "current_position", "participant_id", "status"]);
    expect(payload.participant_id, "the id is carried verbatim, not re-issued").toBe(UUID);
    expect(
      "assessment_number" in payload,
      "the caller cannot pick the per-assessment sequence — the trigger owns it",
    ).toBe(false);
  });

  it("an unknown participantId is refused 404 and mints nothing to satisfy the request", async () => {
    // participantRow defaults to null → no participant exists.
    const { res, json, captured } = await callPost({
      participantId: "00000000-0000-0000-0000-000000000000",
    });
    console.log("  unknown participant ->", res.status, JSON.stringify(json));
    expect(res.status).toBe(404);
    expect(json.error.code).toBe("UNKNOWN_PARTICIPANT");
    expect(
      captured.inserts,
      "an unknown id must NOT mint a participant to make the request succeed",
    ).toEqual([]);
  });

  it("a missing or malformed participantId is refused 400 and never touches the db", async () => {
    for (const body of [
      {},
      { participantId: "not-a-uuid" },
      { participantId: 42 },
      // 36 characters, but NOT a uuid: any-wildcard validation ("36 chars of
      // [0-9a-z-]") would let this through and hand the db a non-uuid id.
      { participantId: "z".repeat(36) },
      undefined,
    ]) {
      const { res, json, captured } = await callPost(body);
      console.log("  body", JSON.stringify(body), "->", res.status, json?.error?.code);
      expect(res.status).toBe(400);
      expect(json.error.code).toBe("INVALID_PARTICIPANT");
      expect(captured.calls.length, "no db call of any kind may be made").toBe(0);
      expect(captured.inserts.length).toBe(0);
    }
  });

  it("returns 503 without touching the db when the database is unconfigured", async () => {
    isDbConfigured.mockReturnValue(false);
    const { res, json, captured } = await callPost({ participantId: UUID });
    expect(res.status).toBe(503);
    expect(json.error.code).toBe("NOT_CONFIGURED");
    expect(captured.calls.length).toBe(0);
    expect(captured.inserts.length).toBe(0);
  });
});

// ===========================================================================
// Provisional creation — anonymous by construction, number trigger-assigned
// ===========================================================================

describe("provisional participant creation supplies no identity and no number", () => {
  it("inserts an EMPTY participant row and reads the number back from the trigger", async () => {
    const { db, captured } = fakeDb({
      insertResult: (table) =>
        table === "participants"
          ? { data: { participant_id: "p-uuid", sfl_number: "7K2Q-9M4X" }, error: null }
          : { data: { session_id: "s-1" }, error: null },
    });
    const { serviceClient } = await import("@/lib/db/client");
    vi.mocked(serviceClient).mockReturnValue(db as never);
    const { createProvisionalParticipant } = await import("@/lib/session/provisional");

    const result = await createProvisionalParticipant();

    const participantInsert = captured.inserts.find((i) => i.table === "participants");
    console.log("  participant insert payload:", JSON.stringify(participantInsert?.payload));
    expect(
      participantInsert?.payload,
      "the row is anonymous by construction — nothing to compute or supply",
    ).toEqual({});
    expect(
      "sfl_number" in (participantInsert?.payload ?? {}),
      "the number is trigger-assigned, never caller-supplied",
    ).toBe(false);

    // The session write is held to the SAME rule as the direct route: the
    // per-assessment sequence is the trigger's, and the call cannot pick it.
    const sessionInsert = captured.inserts.find((i) => i.table === "assessment_sessions");
    console.log("  session insert payload:", JSON.stringify(sessionInsert?.payload));
    expect(
      Object.keys(sessionInsert?.payload ?? {}).sort(),
      "exactly the four system-chosen columns on the session too",
    ).toEqual(["assessment_version", "current_position", "participant_id", "status"]);

    console.log("  returned ->", JSON.stringify(result));
    expect(result.participantId).toBe("p-uuid");
    expect(result.sflNumber, "the number is read back from the row, not computed in app code").toBe(
      "7K2Q-9M4X",
    );
    expect(result.sessionId).toBe("s-1");
  });
});

// ===========================================================================
// Migration content — the only layer with no runtime path (live DB is blocked)
// ===========================================================================

describe("the migrations enforce identity stability at the database", () => {
  it("sfl_number: NOT NULL, trigger-generated, unique, and generate_sfl_number", () => {
    const sql = read("supabase/migrations/20261001000004_sfl_number.sql");
    const triggers = triggerDecls(sql);
    const assignment = triggers.find((t) => t.fn === "assign_sfl_number()");

    // NOT NULL, as an executable statement (comment lines stripped first).
    expect(
      squash(sqlStructure(sql)),
      "the column cannot be left without a number",
    ).toContain(squash("ALTER TABLE participants ALTER COLUMN sfl_number SET NOT NULL"));

    // UNIQUE: a collision reaching the table would make a lookup ambiguous,
    // which §4.2 says must never expose another person's data. A plain (non-
    // unique) index does not satisfy this, so UNIQUE is part of the assertion.
    expect(
      squash(sqlStructure(sql)),
      "the number identifies exactly one participant",
    ).toContain(
      squash(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_participants_sfl_number ON participants(sfl_number);",
      ),
    );

    // The assignment trigger must be wired to the right function, and it must
    // fire BEFORE INSERT — an AFTER trigger cannot set NEW.sfl_number, so the
    // column would be left NULL on an insert that supplies nothing.
    expect(assignment, "trg_assign_sfl_number is declared and executes its function").toMatchObject({
      name: "trg_assign_sfl_number",
      timing: "BEFORE",
      event: "INSERT",
      table: "participants",
    });
  });

  it("protect_sfl_number refuses reassignment but carves out first assignment", () => {
    const sql = read("supabase/migrations/20261001000004_sfl_number.sql");
    const body = functionBody(sql, "protect_sfl_number");
    const blocks = ifBlocks(body);

    // The NULL→number carve-out: an early IF that RETURNs NEW (the backfill
    // and first assignment depend on it). Located as a LIVE block, not a
    // substring that could sit in a comment or dead code.
    const carveOut = blocks.find(
      (b) => b.condition === "OLD.sfl_number IS NULL" && b.action === "RETURN NEW;",
    );
    expect(carveOut, "a live OLD.sfl_number IS NULL → RETURN NEW block").toBeDefined();
    // ORDER MATTERS: on a first assignment the column IS NULL AND the value is
    // DISTINCT FROM OLD (NULL → number). The carve-out must be reached first;
    // reordered, every first assignment hits the refusal.
    expect(
      blocks.indexOf(carveOut!),
      "the carve-out precedes the reassignment guard",
    ).toBeLessThan(
      blocks.findIndex(
        (b) =>
          b.condition === "NEW.sfl_number IS DISTINCT FROM OLD.sfl_number" &&
          b.action.includes("RAISE EXCEPTION"),
      ),
    );

    // The reassignment guard: a live IF whose condition compares NEW against
    // OLD, whose action is a RAISE EXCEPTION. `IF FALSE AND <guard>` yields a
    // different condition string, so a dead guard fails this.
    const guard = blocks.find(
      (b) =>
        b.condition === "NEW.sfl_number IS DISTINCT FROM OLD.sfl_number" &&
        b.action.includes("RAISE EXCEPTION"),
    );
    expect(
      guard,
      "a live reassignment guard whose refusal is RAISE EXCEPTION",
    ).toBeDefined();

    // Wired as an UPDATE guard — a change is what's refused, not an insert.
    const trigger = triggerDecls(sql).find((t) => t.fn === "protect_sfl_number()");
    expect(trigger, "trg_protect_sfl_number executes protect_sfl_number()").toMatchObject({
      name: "trg_protect_sfl_number",
      timing: "BEFORE",
      event: "UPDATE",
      table: "participants",
    });
  });

  it("assign_assessment_number: MAX+1 scoped to the participant, no DEFAULT", () => {
    const sql = read(
      "supabase/migrations/20260930000005_assessment_number_per_participant.sql",
    );
    const body = functionBody(sql, "assign_assessment_number");
    const clean = sqlStructure(body);

    // The SELECT that computes the number, as one normalized statement: MAX,
    // the +1 that makes it the NEXT number (COALESCE default 0 keeps the CHECK
    // >= 1 satisfied), scoped to the participant. `MAX(...) + 1` missing its +1
    // no longer matches; a global MAX (WHERE clause dropped) no longer matches.
    expect(
      squash(clean),
      "COALESCE(MAX(assessment_number), 0) + 1 ... WHERE participant_id = NEW.participant_id",
    ).toContain(
      squash(
        "SELECT COALESCE(MAX(assessment_number), 0) + 1 INTO NEW.assessment_number FROM assessment_sessions WHERE participant_id = NEW.participant_id;",
      ),
    );

    expect(
      squash(sqlStructure(sql)),
      "the colliding DEFAULT is dropped",
    ).toContain(squash("ALTER TABLE assessment_sessions ALTER COLUMN assessment_number DROP DEFAULT;"));

    const trigger = triggerDecls(sql).find((t) => t.fn === "assign_assessment_number()");
    expect(trigger, "trg_assign_assessment_number executes its function").toMatchObject({
      name: "trg_assign_assessment_number",
      timing: "BEFORE",
      event: "INSERT",
      table: "assessment_sessions",
    });
  });

  it("initial_schema: UNIQUE (participant_id, assessment_number)", () => {
    const schema = read("supabase/migrations/20260930000001_initial_schema.sql");
    expect(schema).toMatch(/UNIQUE \(participant_id, assessment_number\)/);
  });
});
