// Provisional participant + session — the anonymous first-time entry path.
//
// Addendum 02 v1.1 §3: "If Opening A = YES: 1. Create an internal
// anonymous/provisional participant_id and new assessment_session behind the
// scenes. 2. Continue directly to Opening B. 3. Continue into the assessment
// without an identity gate."
//
// §5: "Anonymous/provisional first-time sessions must be safely claimable by the
// verified participant when Save My Progress or protected Snapshot retrieval is
// established."
//
// WHAT MAKES A PARTICIPANT "PROVISIONAL". A random UUID, a generated Set for
// Life Number, and nothing else. No name, no email, no phone. That is STRICTLY
// LESS identifying than the flow it replaces, which demanded a name and email
// before the participant could see anything — so this is not a privacy
// regression, it is the removal of an unnecessary data collection.
//
// `claimed_at` stays NULL, which is what marks the row provisional (§5). The
// distinction is recorded explicitly rather than inferred from a missing name: a
// name can be typed by anyone and proves nothing, so presence-of-name would be
// the wrong signal to key on.
//
// THIS IS NOT AN AUTH BYPASS. No protected information is reachable through it:
// the session it creates is empty, and every route that returns participant data
// still requires the session to be completed and still scopes by id. Creating a
// provisional participant grants exactly one capability — starting an assessment.

import { serviceClient } from "../db/client";
import { pinnedVersion } from "./service";

export interface ProvisionalResult {
  participantId: string;
  sessionId: string;
  /** "Your Set for Life Number" — participant-facing, XXXX-XXXX. */
  sflNumber: string;
}

/**
 * Create an anonymous participant and their first session.
 *
 * The Set for Life Number is generated by a database trigger rather than here,
 * so there is exactly one implementation of it and it cannot be bypassed by
 * another caller. That is why this does not compute or supply one.
 */
export async function createProvisionalParticipant(): Promise<ProvisionalResult> {
  const db = serviceClient();

  // No name, no contact — the row is anonymous by construction. `sfl_number` is
  // assigned by trg_assign_sfl_number and is NOT NULL, so a failure to generate
  // one surfaces here rather than as a participant with no way back to their
  // record.
  const { data: participant, error: pErr } = await db
    .from("participants")
    .insert({})
    .select("participant_id, sfl_number")
    .single();

  if (pErr || !participant) {
    throw new Error(`provisional: participant ${pErr?.message ?? "no row returned"}`);
  }

  const participantId = (participant as { participant_id: string }).participant_id;
  const sflNumber = (participant as { sfl_number: string }).sfl_number;

  const { data: session, error: sErr } = await db
    .from("assessment_sessions")
    .insert({
      participant_id: participantId,
      assessment_version: pinnedVersion(),
      status: "in_progress",
      current_position: 1,
    })
    .select("session_id")
    .single();

  if (sErr || !session) {
    throw new Error(`provisional: session ${sErr?.message ?? "no row returned"}`);
  }

  return {
    participantId,
    sessionId: (session as { session_id: string }).session_id,
    sflNumber,
  };
}

/**
 * Attach a verified identity to a provisional participant — §5's "safely
 * claimable".
 *
 * WHY THIS IS A SHARED FUNCTION rather than inline in the callback: claiming is
 * the moment a provisional row becomes a real identity, and it must NOT create a
 * second participant or duplicate the responses already recorded. §14 is
 * explicit: "attach/claim the current provisional participant/session WITHOUT
 * duplicating responses" (emphasis on the constraint, not the mechanism).
 *
 * IT DOES NOT MERGE. §5 forbids automatic merging by name, phone, demographics,
 * IP, or device, and §4.2 of the Master PRD forbids it for identity generally.
 * If the email already belongs to a DIFFERENT participant, this refuses rather
 * than merging the two — that is a decision for a person, not a side effect of
 * an email round trip. The caller decides what to do with the conflict.
 */
export async function claimProvisionalParticipant(args: {
  participantId: string;
  firstName: string;
  lastName: string;
  email: string;
}): Promise<{ claimed: true } | { claimed: false; reason: "email_belongs_to_another" }> {
  const db = serviceClient();

  // Does this email already belong to someone else? Checked BEFORE any write, so
  // a conflict cannot leave the row half-claimed.
  const { data: existing } = await db
    .from("participant_contacts")
    .select("participant_id")
    .eq("contact_type", "email")
    .eq("normalized_value", args.email.trim().toLowerCase())
    .maybeSingle();

  const ownerId = (existing as { participant_id?: string } | null)?.participant_id;
  if (ownerId && ownerId !== args.participantId) {
    return { claimed: false, reason: "email_belongs_to_another" };
  }

  // Name + claim stamp together. `claimed_at` is what marks the row no longer
  // provisional (§5) — it is deliberately NOT set at participant creation.
  const { error: upErr } = await db
    .from("participants")
    .update({
      first_name: args.firstName,
      last_name: args.lastName,
      claimed_at: new Date().toISOString(),
    })
    .eq("participant_id", args.participantId);
  if (upErr) throw new Error(`claim: participant ${upErr.message}`);

  // The contact row is added to the SAME participant. No new participant is
  // created, so the session and every response already stored remain attached to
  // this id — which is the "without duplicating responses" requirement.
  if (!ownerId) {
    const { error: cErr } = await db.from("participant_contacts").insert({
      participant_id: args.participantId,
      contact_type: "email",
      normalized_value: args.email.trim().toLowerCase(),
    });
    if (cErr) throw new Error(`claim: contact ${cErr.message}`);
  }

  return { claimed: true };
}

/**
 * Does this email already belong to a DIFFERENT participant?
 *
 * Used by the claim route to refuse rather than merge. Read-only and separate
 * from `claimProvisionalParticipant` so the route can answer the participant
 * BEFORE sending a verification link — telling someone "saved!" and then failing
 * to attach their identity would be worse than asking them to use another
 * address up front.
 */
export async function queryIfEmailBelongsToAnother(
  participantId: string,
  email: string,
): Promise<boolean> {
  const db = serviceClient();
  const { data } = await db
    .from("participant_contacts")
    .select("participant_id")
    .eq("contact_type", "email")
    .eq("normalized_value", email.trim().toLowerCase())
    .maybeSingle();

  const ownerId = (data as { participant_id?: string } | null)?.participant_id;
  return Boolean(ownerId && ownerId !== participantId);
}
