// Start an assessment with no identity — Addendum 02 v1.1 §2, §3.
//
// §2: "Do not require full name, email verification, or a magic-link round trip
// before a first-time participant can answer this question and begin."
//
// This route is the whole of that change. It creates an anonymous participant
// and an empty session, and returns the participant-facing Set for Life Number
// so the participant can keep it. No name, no email, no verification, no link.
//
// WHAT IT DOES NOT DO, and why the omissions are the point:
//   - it does not collect a name or an email;
//   - it does not send anything;
//   - it does not treat the Set for Life Number as a credential (Addendum 02
//     §4.2: "not a password"). The number is returned so the participant can
//     retain it, and possession of it grants nothing beyond the ability to ask
//     for a lookup — which then requires verification.
//
// §17 requires "First-time participant can begin without full name/email/
// magic-link gate" and "Anonymous/provisional participant/session is created
// safely." Both are satisfied by construction: there is no input to validate
// because there is no input, and the identifier is generated by the database
// rather than supplied by the caller.

import { NextResponse } from "next/server";
import { isDatabaseConfigured, errorBody } from "@/lib/db/client";
import { createProvisionalParticipant } from "@/lib/session/provisional";

export const dynamic = "force-dynamic";

export async function POST() {
  if (!isDatabaseConfigured()) {
    return NextResponse.json(errorBody("NOT_CONFIGURED", "Database is not configured."), {
      status: 503,
    });
  }

  try {
    const { participantId, sessionId, sflNumber } = await createProvisionalParticipant();
    return NextResponse.json(
      {
        participantId,
        sessionId,
        // Participant-facing label is "Your Set for Life Number" (§ operator
        // decision). GTW / Grease the Wheel stays internal and must not appear
        // in anything a participant reads.
        sflNumber,
      },
      { status: 201 },
    );
  } catch {
    // No internal detail is surfaced: a participant starting an assessment has
    // no use for a database error and it would leak schema information.
    return NextResponse.json(
      errorBody("PROVISIONAL_FAILED", "Could not start your assessment."),
      { status: 500 },
    );
  }
}
